name: $(Rev:r)

trigger:
  branches:
    include:
      - master

resources:
  repositories:
  - repository: self
  pipelines:
  - pipeline: policy-ci
    source: ikolomiyets.demo-policy
    trigger:
      branches:
      - master
  - pipeline: customer-ci
    source: ikolomiyets.demo-customer
    trigger:
      branches:
      - master
  - pipeline: frontend-ci
    source: ikolomiyets.demo-frontend
    trigger:
      branches:
      - master


variables:
  - group: demo

stages:
- stage: Test
  displayName: Run integration tests
  jobs:
  - job: Test
    displayName: Test
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: GoTool@0
      inputs:
        version: '1.21.0'
    - script: |
        go version
        go get -v -t -d ./...
      displayName: 'Get dependencies and verify Go version'
    - script: |
        go run gotest.tools/gotestsum@latest --junitfile unit-tests.xml
      displayName: 'Test'
      env:
        ARTIFACTZ_TOKEN: $(artifactz-token)

    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/unit-tests.xml'
        failTaskOnFailedTests: true
      condition: succeededOrFailed()
    - task: push-artifact@1
      displayName: 'Push customers image version to the UAT stage'
      inputs:
        apiToken: $(artifactz.apiToken)
        stage: 'Integration Test'
        name: 'demo-customers'
    - task: push-artifact@1
      displayName: 'Push policy image version to the UAT stage'
      inputs:
        apiToken: $(artifactz.apiToken)
        stage: 'Integration Test'
        name: 'demo-policy'
    - task: push-artifact@1
      displayName: 'Push frontend image version to the UAT stage'
      inputs:
        apiToken: $(artifactz.apiToken)
        stage: 'Integration Test'
        name: 'demo-frontend'
